version: 2
jobs:
  build:
    working_directory: /usr/local/src
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - img-{{ .Branch }}
          paths:
            - /var/cache/img.tar
      - run:
          name: Load Docker Cache
          command: |
            set +o pipefail
            docker load -i /var/cache/img.tar | true
      - run:
          name: Build Docker Image
          command: |
            docker build --cache-from=img -t "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:$(docker -v | cut -d' ' -f3 | tr , ' ' | xargs)" .
      - run:
          name: Save Docker Cache
          command: |
            mkdir -p /var/cache
            docker save -o /var/cache/img.tar "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}"
      - save_cache:
          key: img-{{ .Branch }}-{{ epoch }}
          paths:
            - /var/cache/img.tar
      - deploy:
          name: Push Docker Image
          command: |
            if [ "${CIRCLE_BRANCH}" = master ]
            then
                docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
                docker push "${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:$(docker -v | cut -d' ' -f3 | tr , ' ' | xargs)"
            fi
